const phyllisQuotesArray = ['Close your mouth sweetie, you look like a trout.', 'Andy sings beautifully. And he\'s really good at dancing. He\'s a good speaker. But there\'s just something there you don\'t want to look at.', 'Angela is worse than usual lately, and we have a party to throw. So I googled \"how to deal with difficult people,\" and I got all of this. So we\'re gonna try out some new things today.', 'Look, Michael, it\'s a going-away present so your hands won\'t get cold. It\'s almost done, but you can\'t get them wet, and they can\'t be dry-cleaned either. You have to hand wash without water, wring dry gently, and use a hair dryer on cool.', 'I don\'t think I should walk anymore. You know all I had for breakfast was oatmeal, yogurt, coffee, orange juice and toast. Two poached eggs. And then half a sandwich on the bus. I can\'t.'];
const pamQuotesArray = ['Roy and I just got back from the Poconos. I get ten vacation days a year, and I try to hold off taking them for as long as possible, and this year I got to the third week in January.', 'I feel God in this Chili\'s tonight.', 'I make that one copy, and I become the girl who makes copies. And by the end of the day, I’m the receptionist again.', 'At its worst it was a toxic, political club used to make others feel miserable and left out. At its best, it planned parties.', 'I used to love coming here. The chicken parm is good, big part of my childhood. Oh! Maybe Michael will start dating that too.'];
const stanleyQuotesArray = ['I wake up every morning in a bed that\'s too small, drive my daughter to a school that\'s too expensive. And then I go to work to a job for which I get paid too little. But, on pretzel day... Well, I like pretzel day.', 'It\'s like I used to tell my wife. \"I do not apologize unless I think I\'m wrong and if you don\'t like it, you can leave.\" And I say the same thing to my current wife, and I\'ll say it to my next one too.', 'Did I stutter?!', 'I have been trying to get on jury duty every single year since I was 18 years old. To get to go sit in an air-conditioned room downtown, judging people while my lunch is paid for... That is the life.', 'It\'s true. Around this office, in the past, I have been a little abrupt with people... But the doctor said if I can\'t find a new way to relate more positively to my surroundings I\'m going to die.', 'I took an extra shot of insulin in preparation for this cake today.', 'Boy, have you lost your mind, cause I\'ll help you find it!'];
const dwightQuotesArray = ['As a farmer I know that when an animal is sick sometimes the right thing to do is put it out of its misery. With the electricity we are using to keep Meredith alive, we could power a small fan for two days. You tell me what\'s unethical.', 'No, I disagree. \"R\" is one of the most menacing of sounds. That\'s why they call it murder not \'muckduck\'.', 'You couldn\'t handle my undivided attention.', 'Whenever I\'m about to do something, I think, \"Would an idiot do that?\" And if they would, I do not do that thing.', 'All you need is love? False. The four basic human necessities are air, water, food, and shelter.', 'Identity theft is not a joke, Jim! Millions of families suffer every year!', 'If onlys and justs were candies and nuts, then every day would be Erntedankfest.', 'Are you trying to hurt my feelings? Because if so, you are succeeding. Fortunately, my feelings regenerate twice the speed of a normal man\'s.', 'I now have the strength of a grown man and a little baby.'];
const jimQuotesArray = ['I am about to do something very bold in this job that I\'ve never done before: try.', 'Last week, Dwight found half a joint in the parking lot. And as it turns out, Dwight finding drugs is more dangerous than most people using drugs.', 'I don\'t have a lot of contact with the Scranton branch, but before I left I took a box of Dwight\'s stationery. So from time to time, I send Dwight faxes… from himself… from the future.', 'I miss Dwight. Congratulations, universe. You win.', 'One day, Michael came in complaining about a speed bump on the highway. I wonder who he ran over then.', 'Dwight. This, fits in the palm of my hand. You haven\'t blown \'em up enough. Why have you chosen brown and gray balloons?', 'Yeah. Phyllis called me Michael. And I will always and forever be haunted by that fact.'];
const angelaQuotesArray = ['Dwight has been practicing karate for years. When we were dating, I would help him with his strength training. He would strap me to his chest in a Baby Bjorn made for fat children and do lunges across the farm. I felt like I was flying.', 'I don\'t want to blame anyone in particular. I think everyone\'s to blame.', 'Malls are just awful and humiliating. They\'re just store after store of these horrible sales people making a big fuss out of an adult shopping in a junior section. There are petite adults who are sort of smaller who need to wear, maybe, a kids\' size 10.', 'Sometimes the clothes at GapKids are just too flashy. So, I am forced to go to the American Girl store and order clothes for large colonial dolls.', 'Look, I hate to be \"that\" person but I just don\'t like the general spirit of music.', 'Me? Oh, I\'m fine. I mean, sure, times are leaner now that I\'m separated from the Senator. But my new studio apartment is just fine for me, and Philip, and Tinky, and Crinklepuss, and Bandit 2, and Pawlick Baggins, and Lady Aragorn and their 10 kittens.', 'I actually look forward to performance reviews. I did the youth beauty pageant circuit and I enjoyed that quite a bit. I really enjoy being judged. I believe I hold up very well to even severe scrutiny.', 'I don\'t back down. My sister and I used to be best friends, and we haven\'t talked in 16 years over some disagreement I don\'t even remember. So... Yeah, I\'m pretty good.'];
const kevinQuotesArray = ['I just want to sit on the beach and eat hot dogs. That\'s all I\'ve ever wanted.', 'Mini-cupcakes? As in the mini version of regular cupcakes? Which is already a mini version of cake? Honestly, where does it end with you people?', 'Put back everything in the vending machine, except the fruit.', 'I wanted to eat a pig in a blanket, in a blanket.', 'You think this is a great party? This cake has vegetables in it. Like a salad bar, Robert.', 'I hear Angela\'s party will have double-fudge brownies. But it will also have Angela.', 'Sometimes I feel like everyone I work with is an idiot. And by sometimes, I mean all times. All the time.', 'Nope it\'s not Ashton Kutcher, it\'s Kevin Malone. Equally handsome, equally smart.', 'I got six numbers, one more and it would have been a complete phone number.'];
const meredithQuotesArray = ['You better fix this. I already ditched my uterus and I ain\'t losing any more good parts.', 'I got a beef with that. Um, for the first seven years, I was getting my PhD in School Psychology and they didn\'t show it. Yes, I was getting hammered but, hey, it was college.', 'Michael, you are the reason I drink. You are the reason I live to forget.', 'No. You tell me why my kid is 17 and still can\'t read.', 'What I said was, \"My sister\'s funeral is this weekend.\" Didn\'t say I\'d be there.', 'You guys got to try this pool. No top scum, no band-aids. This thing is choice.', 'Great billboard! Funny, edgy, right up to the line without crossing it, loved it.', 'She\'s right. I had my 2nd kid just for the vacation.', 'I\'ll just have whatever\'s fanciest, unless there\'s ribs. I\'ll just get the other information the day of. I\'ll text you.', 'Stop fighting. Just on St Patrick\'s Day, okay? Just one perfect day a year. No hassles, no problems, no kids', 'No, no, no. You should stay. No, no, no. I have Vienna Sausages and I have napkins. Let me fix you breakfast!'];
const darrylQuotesArray = ['I\'ve never been lucky. And I\'m not talking about the lottery, I\'m talking about stuff like developing a soy allergy at thirty-five. Who gets a soy allergy at thirty-five? And why is soy in everything?', 'I was there. That dude is not engaged. I\'m not a big believer in therapy, but I\'ll go into my own pockets to cover his co-pay.', 'The man is paying me to take Chinese. I will say what I need to say, and soon, I will say it in Chinese.', 'Yes, there used to be a paper clip that would pop up and say \"Looks like you are writing a letter or resume. Would you like help?\" I believe his name was... Clippy.', 'My summer, I, um, blew out my knee playing softball. Ended up watching CNN most of the time. I don\'t know how we\'re going to get out of Afghanistan. I hate the new assistant. He\'s only been here for a week, and I hate him.', 'All I need is Kevin. Dude buys more cookies than everyone combined and then some. When I first started selling cookies he was a relatively thin man. Not a thin man, mind you. Relatively thin.', 'I don\'t wanna prank anymore. Things get real. It\'s not funny. I\'m just gonna be good, stay in my room, go to church, try to do one nice thing per day. I do not wanna prank anymore.', 'When I worked in the warehouse, I was part of that lotto pool. They won ... playing my birthday.', 'What\'d I tell you about building forts in my warehouse?'];
const oscarQuotesArray = ['Angela\'s engaged to a gay man. As a gay man, I\'m horrified. As a friend of Angela\'s, horrified. As a lover of elegant weddings, I\'m a little excited. But overall, horrified.', 'The Dunder Mifflin stock symbol is DMI. Do you know what that stands for? Dummies, morons and idiots. Because that\'s what you\'d have to be to own it. And, as one of those idiots, I believe the board owes me answers.', 'I love a good quitting story. It makes me feel like I have control over my own life. Gives me hope. Maybe I\'ll have one of my own someday. But I dream. So…', 'Look, it doesn\'t take a genius to know that any organization thrives when it has two leaders. Go ahead, name a country that doesn\'t have two presidents. A boat that sets sail without two captains. Where would Catholicism be without the popes?', 'I got Creed. And to tell you the truth, I don\'t know anything about Creed. I know his name\'s Creed. I know he works right over there. I think he\'s Irish and I got him this shamrock keychain.', 'I consider myself a good person. But I\'m gonna try to make him cry.', 'I want to get that image out of my head. The psychological issues that go behind licking a cat are not things I want to go into. Also, I\'m pretty sure she coughed up a hairball.', 'The hospital will provide dictionaries, bring a thesaurus!', 'My God. There is a hardwood floor underneath this carpeting. Why would they do that?', 'The only premature baby in this room is the baby this baby ate.', 'Our office has an unusually large number of... unusually large people. So when something as routine as elevator maintenance happens, and people are forced to expend cardiovascular effort, we have to compare it to the end of time.'];
const creedQuotesArray = ['I\'ve been involved in a number of cults, both as a leader and a follower. You have more fun as a follower. But you make more money as a leader.', 'Nobody steals from Creed Bratton and gets away with it. The last person to do this disappeared. His name: Creed Bratton.', 'I run a small fake I.D. company from my car with a laminating machine that I swiped from the sheriff’s station.', 'I sprout mung beans on a damp paper towel in my desk drawer. Very nutritious, but they smell like death.', 'What is wrong with this woman? She\'s asking about stuff that\'s nobody\'s business. What do I do? Really, what do I do here? I should\'ve written it down. Qua something, uh…qua…quar…quibo, qual…quir-qubity. Uabity assurance! No, no, no, no, no, but I\'m getting close.', 'Not bad for a day in the life of a dog food company.', 'You should see how many supplies I\'ve taken from this place. Honestly, I love stealing.'];
const michaelQuotesArray = ['That\'s what she said!', 'Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me.', 'Sometimes I\'ll start a sentence, and I don\'t even know where it\'s going. I just hope I find it along the way.', 'I love inside jokes. I hope to be a part of one someday.', 'I\'m not superstitious, but I am a little stitious.', 'And I knew exactly what to do. But in a much more real sense, I had no idea what to do.', 'The worst thing about prison was the dementors.', 'Presents are the best way to show how much you care. It\'s a tangible thing you can point at and say, \"Hey man, I love you. This many dollars worth.\"', 'Any man who says he totally understands women is a fool. Because they are un-understandable.', 'I would not miss it for the world. But if something else came up, I would definitely not go.', 'Reverse psychology is an awesome tool. I don’t know if you guys know about it, but, basically, you make someone think the opposite of what you believe. And that tricks them into doing something stupid. Works like a charm.', 'My mind is going a mile an hour.', 'It just seems awfully mean. But sometimes, the ends justify the mean.', 'Well, well, well, how the turntables.', 'You cheated on me? When I specifically asked you not to?', 'That has sort of an oaky afterbirth.', 'I… declare…. bankruptcy!'];
const charactersArray = ['Phyllis', 'Pam', 'Stanley', 'Dwight', 'Jim', 'Angela', 'Kevin', 'Meredith', 'Darryl', 'Oscar', 'Creed'];
const getRandomChar = () => charactersArray[Math.floor(Math.random() * 11)];

const randomCharAndQuote = (character) => {
    switch (character) {
        case 'Phyllis':
            console.log(`Phyllis: ${phyllisQuotesArray[Math.floor(Math.random() * 5)]}`);
            break;
        case 'Pam':
            console.log(`Pam: ${pamQuotesArray[Math.floor(Math.random() * 5)]}`);
            break;
        case 'Stanley':
            console.log(`Stanley: ${stanleyQuotesArray[Math.floor(Math.random() * 7)]}`);
            break;
        case 'Dwight':
            console.log(`Dwight: ${dwightQuotesArray[Math.floor(Math.random() * 9)]}`);
            break;
        case 'Jim':
            console.log(`Jim: ${jimQuotesArray[Math.floor(Math.random() * 7)]}`);
            break;
        case 'Angela':
            console.log(`Angela: ${angelaQuotesArray[Math.floor(Math.random() * 8)]}`);
            break;
        case 'Kevin':
            console.log(`Kevin: ${kevinQuotesArray[Math.floor(Math.random() * 9)]}`);
            break;
        case 'Meredith':
            console.log(`Meredith: ${meredithQuotesArray[Math.floor(Math.random() * 11)]}`);
            break;
        case 'Darryl':
            console.log(`Darryl: ${darrylQuotesArray[Math.floor(Math.random() * 9)]}`);
            break;
        case 'Oscar':
            console.log(`Oscar: ${oscarQuotesArray[Math.floor(Math.random() * 11)]}`);
            break;
        case 'Creed':
            console.log(`Creed: ${creedQuotesArray[Math.floor(Math.random() * 7)]}`);
            break;
    }

};

const printTwoChars = () => {
    let firstChar = getRandomChar ();
    let secondChar = getRandomChar ();
    while (firstChar === secondChar) {
        secondChar = getRandomChar ();
    }
    randomCharAndQuote (firstChar);
    randomCharAndQuote (secondChar);
    console.log(`Michael has made ${firstChar} and ${secondChar} share desks with each other for the day and has decided to offer them some life advice: ${michaelQuotesArray[Math.floor(Math.random() * 17)]}`);
};

printTwoChars();